version: '3'
services:
  ch-server:
    hostname: ch-server
    image: 'yandex/clickhouse-server:19.16.13.54'
    container_name: ch-server
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes: 
      - '/home/vagrant/clickhouse-data:/var/lib/clickhouse'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144 
  # ch-client:
  #   hostname: ch-client
  #   image: 'yandex/clickhouse-client'
  #   container_name: ch-client
  #   command: ['--host', 'ch-server']
