---
 - name: Add vagrant user to docker group
   user:
     name: vagrant
     groups: docker
     append: yes
   become: yes

 - name: Install Docker Python library
   pip: name=docker state=latest

 - name: Install docker-compose
   pip: name=docker-compose state=latest
